db:
  host: localhost
  port: 5432
  name: outer-wilds-db
  user: user
  password: password
env:
  name: dev
frontend:
  url: http://localhost:5173
kafka:
  host: localhost
  port: 9092
  topic:
    planets: planet-positions
    ships: ship-positions
